---
name: Aaron Wenger
date: "`r format(Sys.time(), '%B, %Y')`"
# profilepic: pic.jpg
qualifications: B.S., MA
position: "Ph.D Candidate"
address: "Kalamazoo, Michigan"
email: "aaron.wenger@protonmail.com"
#website:
github: ace-wenger
linkedin: aaron-wenger-a6b7b724a
orcid: 000-0002-1972-3001
aboutme: "I am a Ph.D. candidate in the Mallinson Institute of Science Education, currently preparing my dissertation manuscript. Example work can be found on my Github page in the 'Portfolio' repository. Several hyperlinks to relevant projects are embedded." 
headcolor: e62e00 # for red
docname: CV-air
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Professional Profile

```{r}
tribble(
  ~ what, ~ dummy, ~ institution, ~ loc, ~ details,
  ## Research Interests
  "Research Interests", "",
  "", "", 
  list(
    "1) Meta-research methods, especially meta-analysis and bibliometrics", 
    "2) Computational reproducibility and open science practices", 
    "3) Role of evidence in educational policy and practice"
  ),
  ## Teaching and Public Engagement Interests
  "Teaching and Public Engagement Interests", "",
  "", "", 
  list(
    "1) Scientific methods, experimental design, causal inference, and philosophy of science", 
    "2) Statistical and computational research methods using R, esecially computational reproducibility", 
    "3) History of educational psychology and science education", 
    "4) Introductory and advanced biology subjects"
  ),
  ## Ph.D. Candidate in Science Education
  "Ph.D. Candidate in Science Education", "2017-present", 
  "Western Michigan University", "Kalamazoo, Michigan", 
  list(
    "Currently writing dissertation manuscript; advised and chaired by Dr. William Cobern (concurrently enrolled in Biology MA program until 2021)",
    "Named the \\textbf{2023-2024 Department Graduate Research and Creative Scholar}, in recognition of excellence in research and creative scholarship",
    "Coursework relevant to position includes: \\begin{enumerate} \\item[] 1) Experimental and Quasi-experimental Design for Applied Research and Evaluation \\item[] 2) Fundamentals of Measurement in the Behavioral Sciences \\item[] 3) Survey Research \\item[] 4) Applied Multivariate Statistics \\end{enumerate}"
  ),
  ## Projects/Manuscripts in Progress (WORKNG TITLES)
  "Projects/Manuscripts in Progress (WORKNG TITLES)", "",
  "", "", 
  list(
    "Dissertation: Beyond Average Effects in Education Research: \\textit{Explaining heterogeneity of concept mapping research in science education through meta-regression modeling} \\begin{enumerate} \\item[] \\textbf{Article 1:} Challenges and Solutions for Knowledge Accumulation in Science Education Research \\item[] \\textbf{Article 2:} Concept Mapping in Biology Education: \\textit{A Systematic Review and Meta-Analysis} \\item[] \\textbf{Article 3:} Explaining Heterogeneity in Science Education Research: \\textit{Comparing machine learning models with a priori meta-regression models} \\end{enumerate}",
    "Mapping the Homeschooling Literature: \\textit{A Scoping Review and Source Analysis}"
  ),
  ## Graduate Research Assistant in SAMPI
  "Graduate Research Assistant in Science And Mathematics Program Improvement (SAMPI)", "2021-2023",
  "", "",
  list(
    "Assisted in program evaluation for clients including NSF-funded Professional development for Emerging Education Researchers (PEER) field school,  Kalamazoo Scholars Program, and the Michigan STEM Network (MiSTEM", 
    "Created protocols and evaluation tools (e.g., Qualtric surveys and interview questions)", 
    "Conducted quantitative and qualitative analysis of numerical, ordinal, and textual data", 
    "Wrote internal and external reports summarizing findings"
  )
) %>% detailed_entries(what, dummy, institution, loc, details)
```

# Education

```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  ## Masters
  "M.A. in Biological Sciences", "Western Michigan University", 
  "Kalamazoo, Michigan", "2017-2021",
    list("Master's Thesis Project: Engineered Flagellin Disulfide Variants in Salmonella typhimurium. Advised by Dr. Brian Tripp"),
  ## Bachelors
  "B.S. in Biology-Health Sciences - minors in Chemistry, Ancient (History) Studies", "Cornerstone University", 
  "Grand Rapids, Michigan", "2011-2015",
    list("Recipient of the Ronald Meyer Academic Scholar, Dean's list (6 of 7 semesters), and President's Scholarship",
         "Senior Thesis Project: a meta-study of the neural crest as a mechanism for vertebrate phenotypic diversity",
         "Internship: Hesse Memorial Archaelogical Laboratory, learned and applied zooarcheological techniques with animal bone remains")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

\pagebreak

# Portfolio and Further Education

## Software for Statistics and Data Science

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "R", "substantial programming experience with base R, the Rstudio IDE, and common packages such as 'ggplot'", "See \\href{https://github.com/ace-wenger/ConceptMapping_inBioEd}{\\textit{ConceptMapping-inBioEd}}", "", "", 
  "Git and GitHub", "substantial experience creating and mangaging projects using Git version control and the GitHub collaboration platform", "See my GitHub account for several public projects", "", "",
  "Analysis Pipeline Tools", "substantial experience implementing data analysis pipelines with the `targets` and `renv` R packages", "See \\href{https://github.com/ace-wenger/ConceptMapping_inBioEd}{\\textit{ConceptMapping-inBioEd}}", "", "",
  "SPSS and SAS", "minor programming experience with both", "See \\href{https://github.com/ace-wenger/Portfolio/sas}{\\textit{Portfolio/sas}}", "", "", 
  "Excel VBA","minor programming experience", "See \\href{https://github.com/ace-wenger/Portfolio/vba}{\\textit{Portfolio/vba}}", "", ""
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> (<portfolio_link>)", .open = "<", .close = ">"), .protect = FALSE)
```

## Software for Documentation and Reporting

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "Microsoft Office Suite", "extensive experience with Word, PowerPoint, Excel, Outlook, and Teams", "", "", "",
  "Quarto", "substantial experience creating reports and presentations", "", "", "",
  "Rmarkdown", "substantial experience creating data analysis notebooks, reports, and other documents such as this CV", "", "", "",
  "LaTeX", "minor working experience using the TeXworks IDE such as in this CV", "", "", "",
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> (<portfolio_link>)", .open = "<", .close = ">"), .protect = FALSE)
```

## Other Software

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "Qualtrics", "substantial experience in creating survey forms, distributing to program participants, and processing results", "", "", "",
  "Google Forms", "substantial experience in creating survey forms and processing results", "", "", "",
  "Abstrackr and MetaReviewer", "substantial experience in these platforms for meta-research studies", "", "", ""
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> <portfolio_link>", .open = "<", .close = ">"), .protect = FALSE)
```

## Workshops and Online Courses

```{r}
tribble(
  ~ what, ~ detail, ~ semester, ~ dummy1, ~ dummy2,
  "Introduction to Systematic Reivew and Meta-Analysis", "a John Hopkins University course hosted by Coursera", 
  "2020", "", "",
  
  "AERA-ICPSR PEERS", "attended several in this workshop series including: Modern Meta-analysis, Cutting-edge Quatitative and Computational Methods for STEM Education, and Introduction to qualitative meta-synthesis methods",
  "2020-21", "", "",
  
  "Bibliometrics Training Series", "put on by the NIH Library", 
  "2021", "", "",
  
  # "Getting Started with SAS Programming", "a SAS course hosted by Coursera",
  # "2021", "", "",
  
  "Excel VBA Programming", "video course introducing VBA programming and various applications such as macro implementation, userforms, and webscraping",
  "2022", "", "",
  
  # "Hands-on Programming in R", "online book course by Hadley Wickham of Posit",
  # "2022", "", "",
  
  # "Happy Git and GitHub for the userR", "online book course introducing basic and more advanced applications of GitHub version control",
  # "2022", "", "",
  
  # "Data Science in R", "online book course by Hadley Wickham of Posit",
  # "2022", "", "",
  
  "Research Transparency Online Course", "put on by the Berkeley Initiative for Transparency in the Social Sciences (BITSS)",
  "2022", "", "",
  
  "Reproducible Research Tutorial Series", "online course by Dr. Schloss of the University of Michigan, supported by NIH",
  "2022", "", "",

  "Instats: Path analysis with interactions and indirect effects in R", "Taught by Michael Zyphur",
  "2022", "", "",

  # "The Turing Way", "online community-sourced course supported by the Alan Turing Institute",
  # "2023", "", "",
  
  "Instats: Confirmatory factor analysis and structural equation modeling in R", "Taught by Michael Zyphur and with certificate of completion",
  "2023", "", "",

  "Instats: Meta-analytic structural equation modeling", "Taught by Mike Cheung and with certificate of completion",
  "2023", "", "",
  
  "Evidence Synthesis and Meta-Analysis in R (ESMAR) Conference", "several workshops including: Advanced GitHub, Screening studies for eligibility in evidence syntheses",
  "2023", "", ""
) %>% 
  arrange(desc(semester)) %>%
  brief_entries(glue::glue("\\textbf{<what>}: <detail>", .open = "<", .close = ">"), semester, .protect = FALSE)
```

# Teaching Experience

```{r}
tribble(
  ~ what, ~ when, ~ with, ~ where, ~why,
    "Teaching Assistant", "2017-2021", 
  "Western Michigan University", "Kalamazoo, Michigan", 
  list("Served as instructor of record, teaching science courses for primary education majors",
       "CHEM 2800 - Physical Science for Elementary Educators: a inquiry-based, activity-centered course covering basic chemical and physical science principles",
       "BIOS 1700 - Life Science for Non-Majors: a laboratory-lecture-based content course covering major topics in the life sciences; taught first as an in-person course then \\textbf{independently adapted to a virtual, partially synchronous implementation} for 2020-21 fall/spring semesters",
       "GEOG 1900 - Exploring Earth Science, the Atmosphere: A laboratory-based course covering basic earth science principles with an emphasis on the atmosphere; taught as a virtual, partially synchronous course"),
  "Lecturer for Pre-Med Intiative", "2018", 
  "", "", 
  list("A student-led program for MCAT exam preparation"),
  
  "Teacher", "2015-2017", 
  "Friday Addition (FA) and Homeschool Ancillary Program (HsAP)", "Michigan",
  list("Developed and taught 9th grade biology and 7th grade general science classes at FA and HsAP as well as 10th grade chemistry at HsAP"),
  
  "College Tutor and Laboratory Assistant", "2012-2015",
  "Cornerstone University","Grand Rapids, Michigan",
  list("Tutored college undergraduates for courses in genetics, chemistry, physics, math, and history with 480 hours of experience",
       "Assisted in stockroom, ordering materials, organizing activities, and grading laboratory reports"),
  ) %>%
  arrange(desc(when)) %>%
  detailed_entries(what, when, with, where, why)
```

# Grants and Professional Experience/Service

```{r}
tribble(
  ~ what, ~ detail, ~ when, ~ with,
  "Graduate Student Research Grant", 
    "Institutional grant secured for biology master thesis project", 
    "2019", "Western Michigan University",
  "Graduate Student Research Grant",
    "Secured for Science Education Research Project", 
    "2021", "Western Michigan University",
  "Graduate Student Panel Reviewer", 
    "Served as graduate student reviewer for Division D (Measurement \\& Research Methodologies) and SIG-SRMA (Systematic Review and Meta-Analysis special interest group)", 
    "2024", "AERA Annual Meeting"
  ) %>%
  arrange(desc(when)) %>%
  brief_entries(glue::glue("\\textbf{<what>} \\newline <detail>", .open = "<", .close = ">"), when, with, .protect = FALSE)
```

# Presentations and Publications
```{r}
bibliography_entries("Conference_Presentations.bib")
```
