---
name: Aaron Wenger
date: "`r format(Sys.time(), '%B, %Y')`"
# profilepic: pic.jpg
qualifications: B.S., MA
position: PhD
address: 2226 Frederick Ave.  |  Kalamazoo, Michigan 49008
number: (616) 799-4352
email: aaron.wenger@protonmail.com
#website:
headcolor: e62e00
# for red
github: ace-wenger
#linkedin:
# orchid: 
aboutme: "PhD applicant with experience in study design, statistical analysis, data management, and STEM education teaching and research seeking the Post-Graduate Fellow position at Science and Mathematics Program Improvement (SAMPI)."
docname: SAMPI resume
output: 
  vitae::awesomecv:
  keep_tex: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Key Skills

```{r}
tribble(
  ~ what, ~ dummy, ~ institution, ~ loc, ~ details,
 "Study Design, Data Management, and Statistical Analysis", "",
  "", "", 
  list(
    "Created study assessment tool and applied it to 400+ experimental and quasi-experimental studies judging internal validity and threat of bias",
    "Constructed relational database to collect and organize hierarchically structured data and implemented appropriate data management practices (e.g., data dictionaries)",
    "Designed and implemented analysis pipelines to automatically clean, process, and analyse data in R", 
    "Applied multilevel regression models with appropriate diagnostics"
  ),
  ##
  "Project Management and Communication", "",
  "", "", 
  list(
    "Planned large project requiring 1,500+ hours, identifying the critical path for progress and key deliverables (e.g., analytic results)", 
    "Organized and maintained a working group of peers for related projects",
    "Presented project results to peers and non-experts in multiple venues"
  ),
  ##
  "Diverse Quantative and Qualitative Evaluation Skills", "",
  "", "", 
  list(
    "Created survey tools, interview protocols, various project documents (e.g., memos), and supporting documentation",
    "Conducted numerous interviews for SAMPI, analyzed those interviews and drafted reports",
    "Conducted surveys using Google Forms and Qualtics, analyzed the collected responses, and drafted reports",
    "Reviewed research literature to support work and developed new skills to address challenges")
) %>% detailed_entries(what, dummy, institution, loc, details)
```

# Experience

```{r}
tribble(
  ~ what, ~ dummy, ~ institution, ~ loc, ~ details,
  "Graduate Research Assistant in Science And Mathematics Program Improvement (SAMPI)", "2021-2023",
  "Western Michigan University", "Kalamazoo, Michigan",
  list(
    "Worked on MiSTEM project (among others) under direction of project leads",
    "Created protocols and tools in collaboration with internal staff", 
    "Conducted quantitative and qualitative analysis of continuous, ordinal, and textual data", 
    "Wrote internal and external reports summarizing findings and key action points",
    "Extensive experience collaborating in \\textit {Microsoft Office Suite} products"
  ),
  "Teaching Assistant", "2017-2021", 
  "Western Michigan University", "Kalamazoo, Michigan", 
  list(
    "Taught science courses, including chemistry and biology, as the instructor of record",
    "Independently moved in-person courses to virtual, partially synchronous format making all necessary modifications to course activities and materials")
) %>% detailed_entries(what, dummy, institution, loc, details)
```

# Education

```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "Ph.D. in Science Education", 
  "Western Michigan University", 
  "Kalamazoo, Michigan", 
  "2017-present", 
  list(
    "Named the \\textbf{2023-2024 Department Graduate Research and Creative Scholar}, in recognition of excellence in research and creative scholarship",
    "Learned basic inferential statistics through multivariate analysis using SAS, SPSS, and R",
    "Independently learned data management principles, R programming, and software for computational reproducibility",
    "Leveraged tools for parametrized reporting (Rmarkdown, Quarto) including my dissertation manuscript and this resume"
  ),
  ##
  "M.A. in Biological Sciences", 
  "", 
  "", 
  "2017-2021",
    list("Master's Thesis Project: Engineered Flagellin Disulfide Variants in Salmonella typhimurium"),
  ##
  "B.S. in Biology-Health Sciences - minors in Chemistry, Ancient (History) Studies", "Cornerstone University", 
  "Grand Rapids, Michigan", "2011-2015",
    list("Recipient of the Ronald Meyer Academic Scholar, Dean's list (6 of 7 semesters), and President's Scholarship")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```
