---
name: Aaron Wenger
date: "`r format(Sys.time(), '%B, %Y')`"
# profilepic: pic.jpg
qualifications: B.S., MA
position: Ph.D. Candidate
address: Kalamazoo, Michigan
email: aaron.wenger@protonmail.com
#website:
headcolor: e62e00
# for red
github: ace-wenger
#linkedin:
orchid: 
aboutme: "I am a Ph.D. candidate in the Mallinson Institute of Science Education program. I have a passion for 1) the role and nature of evidence for decisions in education and 2) teaching and learning at all levels and subjects, particularly biology in higher education . Example work can be found on my Github page in the 'Portfolio' repository. Several hyperlinks to relevant projects are embedded." 
docname: CV
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Professional Profile

```{r}
tribble(
  ~ what, ~ dummy, ~ institution, ~ loc, ~ details,
  "Research Interests", "",
  "", "", 
  list(
    "1) Meta-research methods, such as systematic review and meta-analysis", 
    "2) Computational reproducibility and open science practices for data collection, analysis, and reporting", 
    "3) Role of evidence in educational policy and practice"
  ),
  ##
  "Teaching and Public Engagement Interests", "",
  "", "", 
  list(
    "1) Scientific methods, experimental design, causal inference, and philosophy of science", 
    "2) Introductory and advanced biology subjects, particularly microbiology and molecular biology", 
    "3) History of educational psychology and science education", 
    "4) Statistical and computational research methods using R, especially computational reproducibility"
  ),
  ##
  "Ph.D. Candidate in Science Education", "2017-present", 
  "Western Michigan University", "Kalamazoo, Michigan", 
  list("Received 2023-2024 Department Graduate Research and Creative Scholar Award",
       "Currently completing dissertation project with a defense planned for summer 2024; Advised and chaired by Dr. William Cobern"
       # "Coursework relevant to position includes: \\begin{enumerate} \\item[] 1) Experimental and Quasi-experimental Design for Applied Research and Evaluation \\item[] 2) Fundamentals of Measurement in the Behavioral Sciences \\item[] 3) Evaluation II: Evaluating Products, Personnel and Policy \\item[] 4) Applied Multivariate Statistics \\end{enumerate}" 
  ),
  ##
  "Projects/Manuscripts in Progress (WORKNG TITLES)", "",
  "", "", 
  list(
    "Dissertation: Beyond Average Effects in Education Research: \\textit{Explaining heterogeneity of concept mapping research in science education through meta-regression modeling} 
    \\begin{enumerate} 
    \\item[*] Prepared several critical literature reviews.
    \\item[*] Prepared and implemented comprehensive research protocols, including contact memos and several coding protocols evaluated for reliability.
    \\item[*] Constructed reproducible data analysis pipelines in R.
    \\item[*] Implemented and interpreted multi-level, meta-regression models with complex data dependency structures and multiple imputation of missing data.
    \\item[*] Implemented and interpreted random forest machine learning model to explain variation in research results.
    \\end{enumerate}",
    "Mapping the Homeschooling Literature: \\textit{A Scoping Review and Source Analysis}
    \\begin{enumerate}
    \\item[*] Prepared research proposal and preliminary protocols for the collection and processing of bibliometric data regarding academic research on homeschooling
    \\end{enumerate}"
  ),
  ##
  "Graduate Research Assistant in Science And Mathematics Program Improvement (SAMPI)", "2021-2023",
  "", "",
  list(
    "Assisted in program evaluation for clients including NSF-funded Professional development for Emerging Education Researchers (PEER) field school,  Kalamazoo Scholars Program, and the MiSTEM Network", 
    "Created protocols and evaluation tools (e.g., Qualtric surveys and interview protocols)", 
    "Conducted quantitative and qualitative analysis of numerical, ordinal, and textual data", 
    "Wrote internal and external reports summarizing findings"
  )
) %>% detailed_entries(what, dummy, institution, loc, details)
```

# Education

```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "M.A. in Biological Sciences", "Western Michigan University", 
  "Kalamazoo, Michigan", "2017-2021",
    list("Enrolled concurently with science education Ph.D. until degree completion"),
  
  "B.S. in Biology-Health Sciences - minors in Chemistry, Ancient (History) Studies", "Cornerstone University", 
  "Grand Rapids, Michigan", "2011-2015",
    list("Recipient of the Ronald Meyer Academic Scholar, Dean's list (6 of 7 semesters), and President's Scholarship")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

\newpage

# Competancies

## Software for Statistics, Data Science, and Reporting

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "Microsoft Office Suite", "extensive experience with Word, PowerPoint, Excel, Outlook, and Teams", "", "", "",
  "R", "substantial experience with base R, the Rstudio IDE, and common packages. This is an area of active learning and development.", "(See \\href{https://github.com/ace-wenger/ConceptMapping_inBioEd}{\\textit{ConceptMapping-inBioEd}})", "", "", 
  "Quarto and Rmarkdown", "substantial experience creating documents (such as this CV), presentations, and data analysis notebooks which combine narrative text and data analysis code. This is an area of active learning and development.", "", "", "",
  "Git and GitHub", "substantial experience creating and mangaging projects using Git version control and the GitHub collaboration platform", "(See my GitHub account for several public projects). This is an area of active learning and development.", "", "",
  # "Analysis Pipeline Tools", "substantial experience with the `targets` and `renv` R packages", "(See \\href{https://github.com/ace-wenger/ConceptMapping_inBioEd}{\\textit{ConceptMapping-inBioEd}})", "", "",
  "SPSS, SAS, Excel VBA", "minor programming experience with all three", "(See \\href{https://github.com/ace-wenger/Portfolio/sas}{\\textit{Portfolio/sas}} and \\href{https://github.com/ace-wenger/Portfolio/vba}{\\textit{Portfolio/vba}})", "", "",
  "LaTeX", "minor working experience using the TeXworks IDE such as in this CV", "", "", ""
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> <portfolio_link>", .open = "<", .close = ">"), .protect = FALSE)
```

## Competancies for Statistical Data Analysis

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "Inferential Statistics", "Extensive experience through dissertation and SAMPI work in conducting and interpreting hypothesis tests of numeric data (t-tests, ANOVAs, ect.)", "", "", "",
  "Critical Evaluations of Statistical Analyses", "Extensive experience in evaluating statistics in primary studies, including: 1) GRIM test (granularity-related inconsistency means); 2) retrospective power analysis; 3) back-calculation and estimation of summary statistics; and 4) critical assessments of analytic choices", "", "", "",
  "Linear Regression Modeling", "Substantial experience in implementing and interpreting complex linear regression models, including multilevel models. Also some minor experience with multivariate models", "", "", "",
  "Reproducible Data Analysis Pipelines", "Substantial experience in implementing analysis pipelines which enable reproducibility, extensibility, and scalability of data handling and analysis. This is an area of active learning and development.", "", "", "",
  "Handling Missing Data", "Minor experience with characterizing 'missingness' and appropriately implementing multiple imputation. This is an area of active learning and development.", "", "", "",
  "Machine Learning", "Minor experience with random forest algorithm. This is an area of active learning and development.", "", "", "",
  "Data Management and Relational Databases", "Minor experience with creating and using data dictionaries and codebooks. Some experience with buidling and using relational databases (csv tables) in R.", "", "", "",
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> <portfolio_link>", .open = "<", .close = ">"), .protect = FALSE)
```

## Competancies for Research

```{r}
tribble(
  ~ what, ~ detail, ~ portfolio_link, ~ dummy1, ~ dummy2,
  "Writing", "Extensive experience through SAMPI in drafting \\textit{annual reports} incorporating evaluation indices and interviews with project team members. Additional experience in writing \\textit{academic papers} for specialist audieneces, \\textit{literature reviews and protocols} for projects, and \\textit{research proposals}.", "", "", "",
  "Presentations", "Substantial experience creating and giving presenations for general academic audiences", "", "", "",
  "Collaboration and Communication", "Substantial experience in forming collaborations with other graduate students, forming our own research group, and sharing knowledge and skills. Additional experience in communicating with project team members and stakeholders to ensure project success and timely results. This is always an area of active learning and development.", "", "", "",
  "Interviewing", "Substantial experience in drafting portocols and conducting interviews with project members and stakeholders through SAMPI. Was also responsible for transcribing, coding, and summarizing interview results", "", "", "",
  "Survey Design and Analysis", "Substantial experience with Qualtrics and Google Forms in creating survey forms, distributing to program participants, and collecting results. Additional experience in analyzing surveys with likert scales and open-ended questions.", "", "", "",
  "Teacher Observation", "Some experience via SAMPI in observing teachers, assessing their SIOP practices (an instructional framework).", "", "", "",
  "Programming and Automation", "Some experience using R scripts and VBA macros to automate various research tasks, such as data preprocessing or search and retrieval of literature references through database APIs. This is an area of active learning and development", "", "", "",
) %>% 
  brief_entries(glue::glue("\\textbf{<what>}: <detail> <portfolio_link>", .open = "<", .close = ">"), .protect = FALSE)
```

# Teaching Experience

```{r}
tribble(
  ~ what, ~ when, ~ with, ~ where, ~why,
  "Teaching Assistant", "2017-2021", 
  "Western Michigan University", "Kalamazoo, Michigan", 
  list("Served as instructor of record, teaching diferent science courses for primary education majors (including biology, chemistry, and atmospheric science)",
       "Independently adapted an in-person, lecture/laboratory course to virtual , partially synchronous format for 2020-21 fall/spring semesters"
       ),
  
  "Science Teacher", "2015-2017", 
  "Friday Addition (FA) and Homeschool Ancillary Program (HsAP)", "Michigan",
  list("Developed and taught 10th grade chemistry, 9th grade biology, 7th grade general science classes"),
  
  "College Tutor and Laboratory Assistant", "2012-2015",
  "Cornerstone University","Grand Rapids, Michigan",
  list("Tutored college undergraduates for courses in genetics, chemistry, physics, math, and history",
       "Assisted in stockroom, ordering materials, organizing activities, and grading laboratory reports"),
) %>%
  detailed_entries(what, when, with, where, why)
```

# Presentations and Publications

```{r}
bibliography_entries("Conference_Presentations.bib")
```
